services:
  - type: web
    name: local-elections-nl-2026
    runtime: static
    staticPublishPath: .
    routes:
      - type: redirect
        source: /
        destination: /elect
      - type: rewrite
        source: /elect
        destination: /elect/index.html
